### ISSUE TITLE
Add icons for tech stack

### ISSUE THREAD

**Issue by kohchihao** [CanvasCodeForCommunity/canvas#10]
- In home page : Add different icons for the different tech stack used
- In each event page : Add the different icons used for that particular event. 

Different tech used 
- NXT 
- Scratch 
- Wonder Robots (Dash Dot Cue)
- AppInventor 
- Pixar in a Box
- Machine Learning for Kids
- MBot
- MicroBot
- ScratchJr

**Comment by jinyingtan** [comment]
Solved!
